name: Check DESCRIPTION File

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-description-file:
    if: ${{ github.event.pull_request.head.repo.fork == true }} # Only run on PRs from forks
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Check if the DESCRIPTION file exists
      - name: Verify DESCRIPTION file exists
        run: |
          if [ ! -f "DESCRIPTION" ]; then
            echo "ERROR: DESCRIPTION file is missing."
            exit 1
          else
            echo "DESCRIPTION file exists."
          fi

      - name: Check for package name in DESCRIPTION
        run: |
          PACKAGE_NAME=$(cat DESCRIPTION | grep "^Package:" | awk '{print $2}')
          if [ -z "$PACKAGE_NAME" ]; then
            echo "Error: Package name not found in meta.yaml" >&2
            exit 1
          fi
          echo "Package name OK: $PACKAGE_NAME"
        shell: bash
